services:
  app-v1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
    ports:
      - "8081:3000"
    environment:
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
    depends_on:
      - postgres
    networks:
      - app_network
    deploy:
      replicas: 2

  app-v2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
    ports:
      - "8081:3000"
    environment:
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
    depends_on:
      - postgres
    networks:
      - app_network
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app-v1
      - app-v2

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ada-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - app_network

volumes:
  postgres-data:
  redis-data:


networks:
  app_network:
    driver: bridge
